### ISSUE TITLE
Hardware / Software version (KS01_V5.12) is not supported by this adapter!

### ISSUE THREAD

**Issue by apeXerX** [marvingrieger/ioBroker.pallazza#17]
Hello, is there a possibility to install the old version from the adapter via github. And Which Version is supported ?

**Comment by marvingrieger** [comment]
Hey,

since this is an oven, I configured the adapter to terminate itself if an unknown hardware/software version is present.
However, each new combination can be unlocked.

The combination KS01_V5.12 is unlocked in this branch:

https://github.com/marvingrieger/ioBroker.pallazza/tarball/KS01_V5.12

Please install the adapter using this URL and test ...

... if the adapter works as expected
... if you're seeing messages in the log, saying that some states are missing (Message: "State XYZ does not exist")

If everything works as expected, I will merge the branch to the master.

Can you tell me, which oven you're using in particular?

Best regards

**Comment by apeXerX** [comment]
Hey,

I installed the adapter.

Now it works fine , No errors anymore. Thank you very much.
My Oven is the HSP Pallazza III.

Best regards

**Comment by marvingrieger** [comment]
Hey,

thanks for your feedback, I merged the branch to the master.

Regarding the oven: Can you check if you find additional information about the type?
Usually, its something like "HSP **_6_** PALLAZZA-III **_519.08_**"

Best regards

**Comment by apeXerX** [comment]
hey,

also in der Anleitung steht der Typ HSP 6 Pallazza III 519.08

Gruß ;)

**Comment by marvingrieger** [comment]
Danke, habe ich in der Beschreibung aufgenommen!
